version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.18.1
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            cd frontend && docker build -t new-frontend-final --platform linux/amd64 .
      - run:
          name: Login
          command: |
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run:
          name: Push
          command: |
            docker tag new-frontend-final tuandoan1411/test-deploy:latest && docker push tuandoan1411/test-deploy:latest  
            
            
