version: 2.1
jobs:
  test_frontend:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies and run tests (you can add your own tests)
      - run:
          name: Install Frontend Dependencies
          command: cd frontend && npm install
      - run:
          name: Build Frontend
          command: cd frontend && npm run build