version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: cd frontend && docker build -t new-frontend-final --platform linux/amd64 .


workflows:
  my-workflow:
    jobs:
      - hello-job