version: 2.1
jobs:
  test-frontend:
    docker:
      - image: cimg/node:18.18.1
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
          docker_layer_caching: true
      - run:
          name: Install Dependencies
          command: |
            cd frontend && npm install
      - run:
          name: Start App
          command: |
            cd frontend && npm test --passWithNoTests
  test-backend:
    docker:
      - image: cimg/node:18.18.1
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
          docker_layer_caching: true
     - run:
          name: Install Mocha global
          command: npm install --prefix=$HOME/.local --global mocha
      - run:
          name: Install Dependencies
          command: |
            cd backend && npm install
      - run:
          name: Start App
          command: |
            cd backend && mocha
  build-docker:
    docker:
      - image: cimg/node:18.18.1
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            cd frontend && docker build -t new-frontend-final --platform linux/amd64 .
      - run:
          name: Login
          command: |
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run:
          name: Push
          command: |
            docker tag new-frontend-final tuandoan1411/test-deploy:latest && docker push tuandoan1411/test-deploy:latest  
            

  install-aws:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            pip install awscli
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
            aws autoscaling start-instance-refresh --auto-scaling-group-name final-asg  --preferences "MinHealthyPercentage=30,InstanceWarmup=300"
            
            

workflows:
  version: 2
  test-deploy:
    jobs:
      - test-frontend
      - test-backend
      - build-docker:
          requires:
            - test-frontend
            - test-backend
          filters:
            branches:
              only: main
      - install-aws:
          requires:
            - build-docker
          filters:
            branches:
              only: main

