version: 2.1
jobs:
  build-docker:
    docker:
      - image: cimg/node:18.18.1
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.23
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            cd frontend && docker build -t new-frontend-final --platform linux/amd64 .
      - run:
          name: Login
          command: |
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run:
          name: Push
          command: |
            docker tag new-frontend-final tuandoan1411/test-deploy:latest && docker push tuandoan1411/test-deploy:latest  
            

  install-aws:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            pip install awscli
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws autoscaling start-instance-refresh --auto-scaling-group-name final-asg  --preferences "MinHealthyPercentage=30,InstanceWarmup=300"
            
            

workflows:
  version: 2
  test-deploy:
    jobs:
      - install-aws:
          requires:
            - build-docker

